/*
 * Copyright (c) 2014 Amlogic, Inc. All rights reserved.
 *
 * This source code is subject to the terms and conditions defined in the
 * file 'LICENSE' which is part of this source code package.
 *
 * Description: header file
 */

#ifndef __SSM_HANDLER_H__
#define __SSM_HANDLER_H__

#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <errno.h>
#include <string>
#include <utils/threads.h>
#include <vector>
#include <memory>

typedef enum SSM_status_e
{
    SSM_HEADER_INVALID = 0,
    SSM_HEADER_VALID = 1,
    SSM_HEADER_STRUCT_CHANGE = 2,
} SSM_status_t;

enum{
    CHKSUM_PROJECT_ID_OFFSET = 0,
    CHKSUM_MAC_ADDRESS_OFFSET = 1,
    CHKSUM_HDCP_KEY_OFFSET = 2,
    CHKSUM_BARCODE_OFFSET = 3,
    SSM_RSV_W_CHARACTER_CHAR_START = 10,
    SSM_CR_START = 11,
    SSM_MARK_01_START = 12,
    SSM_MARK_02_START = 13,
    SSM_MARK_03_START = 14,
    SSM_RSV0 = 20,
    SSM_RW_FBMF_START = 21,
    SSM_RW_DEF_HDCP_START = 22,
    SSM_RW_POWER_CHANNEL_START = 23,
    SSM_RW_LAST_SOURCE_INPUT_START = 24,
    SSM_RW_SYS_LANGUAGE_START = 25,
    SSM_RW_AGING_MODE_START = 26,
    SSM_RW_PANEL_TYPE_START = 27,
    SSM_RW_POWER_ON_MUSIC_SWITCH_START = 28,
    SSM_RW_POWER_ON_MUSIC_VOL_START = 29,
    SSM_RW_SYS_SLEEP_TIMER_START = 30,
    SSM_RW_INPUT_SRC_PARENTAL_CTL_START = 31,
    SSM_RW_PARENTAL_CTL_SWITCH_START = 32,
    SSM_RW_PARENTAL_CTL_PASSWORD_START = 33,
    SSM_RW_SEARCH_NAVIGATE_FLAG_START = 34,
    SSM_RW_INPUT_NUMBER_LIMIT_START = 35,
    SSM_RW_SERIAL_ONOFF_FLAG_START = 36,
    SSM_RW_STANDBY_MODE_FLAG_START = 37,
    SSM_RW_HDMIEQ_MODE_START = 38,
    SSM_RW_LOGO_ON_OFF_FLAG_START = 39,
    SSM_RW_HDMIINTERNAL_MODE_START = 40,
    SSM_RW_DISABLE_3D_START = 41,
    SSM_RW_GLOBAL_OGO_ENABLE_START = 42,
    SSM_RW_LOCAL_DIMING_START = 43,
    SSM_RW_VDAC_2D_START = 44,
    SSM_RW_VDAC_3D_START = 45,
    SSM_RW_NON_STANDARD_START = 46,
    SSM_RW_ADB_SWITCH_START = 47,
    SSM_RW_SERIAL_CMD_SWITCH_START = 48,
    SSM_RW_CA_BUFFER_SIZE_START = 49,
    SSM_RW_NOISE_GATE_THRESHOLD_START = 50,
    SSM_RW_DTV_TYPE_START = 51,
    SSM_RW_UI_GRHPHY_BACKLIGHT_START = 52,
    SSM_RW_FASTSUSPEND_FLAG_START = 53,
    SSM_RW_BLACKOUT_ENABLE_START = 54,
    SSM_RW_PANEL_ID_START = 55,
    SSM_RSV_1 = 80,
    SSM_RSV_2 = 150,
    VPP_DATA_POS_COLOR_DEMO_MODE_START = 151,
    VPP_DATA_POS_COLOR_BASE_MODE_START = 152,
    VPP_DATA_POS_TEST_PATTERN_START = 153,
    VPP_DATA_POS_DDR_SSC_START = 154,
    VPP_DATA_POS_LVDS_SSC_START = 155,
    VPP_DATA_POS_DREAM_PANEL_START = 156,
    VPP_DATA_POS_BACKLIGHT_REVERSE_START = 157,
    VPP_DATA_POS_BRIGHTNESS_START = 158,
    VPP_DATA_POS_CONTRAST_START = 159,
    VPP_DATA_POS_SATURATION_START = 160,
    VPP_DATA_POS_HUE_START = 161,
    VPP_DATA_POS_SHARPNESS_START = 162,
    VPP_DATA_POS_COLOR_TEMPERATURE_START = 163,
    VPP_DATA_POS_NOISE_REDUCTION_START = 164,
    VPP_DATA_POS_SCENE_MODE_START = 165,
    VPP_DATA_POS_PICTURE_MODE_START = 166,
    VPP_DATA_POS_DISPLAY_MODE_START = 167,
    VPP_DATA_POS_BACKLIGHT_START = 168,
    VPP_DATA_POS_RGB_GAIN_R_START = 169,
    VPP_DATA_POS_RGB_GAIN_G_START = 170,
    VPP_DATA_POS_RGB_GAIN_B_START = 171,
    VPP_DATA_POS_RGB_POST_OFFSET_R_START = 172,
    VPP_DATA_POS_RGB_POST_OFFSET_G_START = 173,
    VPP_DATA_POS_RGB_POST_OFFSET_B_START = 174,
    VPP_DATA_POS_DBC_START = 175,
    VPP_DATA_PROJECT_ID_START = 176,
    VPP_DATA_POS_DNLP_START = 177,
    VPP_DATA_POS_PANORAMA_START = 178,
    VPP_DATA_APL_START = 179,
    VPP_DATA_APL2_START = 180,
    VPP_DATA_BD_START = 181,
    VPP_DATA_BP_START = 182,
    VPP_DATA_RGB_START = 183,
    VPP_DATA_COLOR_SPACE_START = 184,
    VPP_DATA_USER_NATURE_SWITCH_START = 185,
    VPP_DATA_GAMMA_VALUE_START = 186,
    VPP_DATA_DBC_BACKLIGHT_START = 187,
    VPP_DATA_DBC_STANDARD_START = 188,
    VPP_DATA_DBC_ENABLE_START = 189,
    VPP_DATA_POS_FBC_BACKLIGHT_START = 190,
    VPP_DATA_POS_FBC_ELECMODE_START = 191,
    VPP_DATA_POS_FBC_COLORTEMP_START = 192,
    VPP_DATA_POS_FBC_N310_BACKLIGHT_START = 193,
    VPP_DATA_POS_FBC_N310_COLORTEMP_START = 194,
    VPP_DATA_POS_FBC_N310_LIGHTSENSOR_START = 195,
    VPP_DATA_POS_FBC_N310_MEMC_START = 196,
    VPP_DATA_POS_FBC_N310_DREAMPANEL_START = 197,
    VPP_DATA_POS_FBC_N310_MULTI_PQ_START = 198,
    VPP_DATA_POS_N311_VBYONE_SPREAD_SPECTRUM_START = 199,
    VPP_DATA_POS_N311_BLUETOOTH_VAL_START = 200,
    VPP_DATA_EYE_PROTECTION_MODE_START = 201,
    VPP_DATA_DNLP_MODE_START = 202,
    VPP_DATA_DNLP_GAIN_START = 203,
    VPP_DATA_POS_LOCAL_CONTRAST_MODE_START = 204,
    VPP_DATA_POS_LAST_PICTURE_MODE_START = 205,
    VPP_DATA_POS_AIPQ_ENABLE_START = 206,
    VPP_DATA_POS_SMOOTH_PLUS_START = 207,
    VPP_DATA_POS_HDR_TMO_START = 208,
    VPP_DATA_POS_BLACK_EXTENSION_MODE_START = 209,
    VPP_DATA_POS_DEBLOCK_MODE_START = 210,
    VPP_DATA_POS_DEMOSQUITO_MODE_START = 211,
    VPP_DATA_POS_COLORGAMUT_START = 212,
    VPP_DATA_POS_MCDI_MODE_START = 213,
    SSM_RSV3 = 250,
    TVIN_DATA_POS_SOURCE_INPUT_START = 251,
    TVIN_DATA_CVBS_STD_START = 252,
    TVIN_DATA_POS_3D_MODE_START = 253,
    TVIN_DATA_POS_3D_LRSWITCH_START = 254,
    TVIN_DATA_POS_3D_DEPTH_START = 255,
    TVIN_DATA_POS_3D_TO2D_START = 256,
    TVIN_DATA_POS_3D_TO2DNEW_START = 257,
    SSM_RSV4 = 280,
    CUSTOMER_DATA_POS_HDMI1_EDID_START = 281,
    CUSTOMER_DATA_POS_HDMI2_EDID_START = 282,
    CUSTOMER_DATA_POS_HDMI3_EDID_START = 283,
    CUSTOMER_DATA_POS_HDMI4_EDID_START = 284,
    CUSTOMER_DATA_POS_HDMI_HDCP_SWITCHER_START = 285,
    CUSTOMER_DATA_POS_HDMI_COLOR_RANGE_START = 286,
    CUSTOMER_DATA_POS_DYNAMIC_BACKLIGHT = 287,
    CUSTOMER_DATA_POS_EDGE_ENHANCER = 288,
    CUSTOMER_DATA_POS_MPEG_NOISE_REDUCTION = 289,
    CUSTOMER_DATA_POS_DYNAMIC_CONTRAST = 290,
    CUSTOMER_DATA_POS_AUTO_ASPECT = 291,
    CUSTOMER_DATA_POS_43_STRETCH = 292,
    CUSTOMER_DATA_POS_SCREEN_COLOR_START = 293,
    CUSTOMER_DATA_POS_CHANNEL_LOCK_EN_START = 294,
    VPP_DATA_POS_MEMC_MODE_START = 302,
    VPP_DATA_POS_MEMC_DEBLUR_LEVEL_START = 303,
    VPP_DATA_POS_MEMC_DEJUDDER_LEVEL_START = 304,
    SSM_DATA_MAX,
};

typedef enum ssm_source_input_e {
    SSM_SOURCE_INVALID = -1,
    SSM_SOURCE_TV = 0,
    SSM_SOURCE_AV1,
    SSM_SOURCE_AV2,
    SSM_SOURCE_YPBPR1,
    SSM_SOURCE_YPBPR2,
    SSM_SOURCE_HDMI1,
    SSM_SOURCE_HDMI2,
    SSM_SOURCE_HDMI3,
    SSM_SOURCE_HDMI4,
    SSM_SOURCE_VGA,
    SSM_SOURCE_MPEG,
    SSM_SOURCE_DTV,
    SSM_SOURCE_SVIDEO,
    SSM_SOURCE_IPTV,
    SSM_SOURCE_DUMMY,
    SSM_SOURCE_SPDIF,
    SSM_SOURCE_ADTV,
    SSM_SOURCE_MAX,
} ssm_source_input_t;

struct SSMHeader_section1_t
{
    unsigned int magic;
    unsigned int version;//count by ID and its size
    unsigned int count;//count by column of excel
    unsigned int rsv[6];//reserve
};

struct SSMHeader_section2_t
{
    unsigned int id;  //Id index
    unsigned int addr;//Id's addr
    unsigned int size;//this item size
    unsigned int valid;
    unsigned char rsv[6];
};

extern struct SSMHeader_section1_t gSSMHeader_section1;
extern struct SSMHeader_section2_t gSSMHeader_section2[];

class SSMHandler
{
public:
    static SSMHandler* GetSingletonInstance(const char *SSMHandlerPath);
    virtual ~SSMHandler();
    SSM_status_t SSMVerify(void);
    bool SSMRecreateHeader(void);
    unsigned int SSMGetActualAddr(int id);
    unsigned int SSMGetActualSize(int id);

private:
    int mFd;
    static SSMHandler *mSSMHandler;
    SSMHeader_section1_t mSSMHeader_section1;
    static android::Mutex sLock;
    char mSSMHandlerPath[128];

    bool Construct();
    explicit SSMHandler();
    SSM_status_t SSMSection1Verify();
    SSM_status_t  SSMSection2Verify(SSM_status_t);
    SSMHandler& operator = (const SSMHandler&);
};


#endif
