tv_firmware_files := \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8723b_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8723b_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8723bs_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8723bs_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8723bs_VQ0_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8723bs_VQ0_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8723bu_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8723d_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8723d_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8723ds_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8723ds_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8733b_8723f_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8733b_8723f_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8761a_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8761a_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8761at_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8761at_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8761au8192ee_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8761au8812ae_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8761au_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8761aw8192eu_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8761aw8192eu_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8821a_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8821a_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8821as_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8821as_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8821c_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8821c_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8821cs_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8821cs_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8822b_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8822b_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8822bs_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8822bs_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8822c_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8822c_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8822cs_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8822cs_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8822e_8822c_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8822e_8822c_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8822es_8822cs_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8822es_8822cs_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8761b_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8761b_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8761bt_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8761bt_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8725a_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8725a_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8723f_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8723f_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8723fs_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8723fs_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8852as_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8852as_config_vendor \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8852as_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8852au_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8852au_config_vendor \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8852au_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8852bs_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8852bs_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8852bu_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8852bu_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8852cu_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8852cu_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8852cs_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8852cs_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8852bps_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/TV/rtl8852bps_fw

PRODUCT_COPY_FILES += $(call copy-files,$(tv_firmware_files),$(TARGET_COPY_OUT_VENDOR)/firmware)
